### ISSUE TITLE
Requirements check results for browser: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by qin9smile** [apache/cordova-browser#74]
cordova version: 8.1.2 (cordova-lib@8.1.1)

node version: v11.11.0

nvm version: v6.7.0

![image](https://user-images.githubusercontent.com/12714985/54108099-0546b500-4416-11e9-8d63-459141340126.png)

maybe i do something wrong?

**Comment by erisu** [comment]
Hi @	qin9smile,

This should have already been fixed in PR https://github.com/apache/cordova-browser/pull/61 and release in `cordova-browser@6.0.0`.
