### ISSUE TITLE
Build steps to use in angular cli

### ISSUE THREAD

**Issue by koraysels** [apache/cordova-browser#77]
I am using some cordova plugins like Camera and native audio. 
Also it is a hybrid web/ios/android app. It would be cool if we could continue use angular cli for live reloading and compilation of typescript etc.. And have cordova and cordova_plugins in the browser. Right now I can only use ```cordova run browser``` to have the deviceready and native audio/camera support. Is there a wat to have this inside the angular app ?

**Comment by brodybits** [comment]
I am very sorry to say that I do not really follow your question.

It sounds like a nice idea but I don’t think any of us have the time to support that kind of features right now.

I recommend you check out Ionic and the new Capacitor framework. I think they used to work directly with Angular and do support live reloading. Also I think there is no need to wait for the `deviceready` event on Capacitor. May not be quite as mature as Cordova but may be a better fit for your needs.

Closing for now, thanks for your interest.
