### ISSUE TITLE
page lifecycle

### ISSUE THREAD

**Issue by benitogf** [apache/cordova-browser#79]
# Bug Report

## Problem

The [cordova-android lifecycle](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#lifecycle-guide) clashes with the [page lifecycle spec](https://wicg.github.io/page-lifecycle/spec.html).

### What is expected to happen?

There should be some integration between cordova lifecycle and the page lifecycle

### What does actually happen?

The cordova even 'resume' name clashes with 'resume' of page lifecycle

## Information

The browser `pause` event could be a proxy of `freeze`. currently `pause`  will trigger even on a browser tab change, which makes sense on the mobile webview, but not so much on a browser.

### Command or Code

The easiest way to test integration with page lifecycle that I found so far is with `chrome://discards/` as stated here https://developers.google.com/web/updates/2018/07/page-lifecycle-api#testing-your-app-in-the-frozen-and-discarded-states

### Environment, Platform, Device

Tested with cordova-android and cordova-browser

### Version information

Cordova: 9.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
> The [cordova-android lifecycle](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#lifecycle-guide) crashes

What's the connection to `cordova-browser` here?

**Comment by benitogf** [comment]
think that cordova-browser could use the page lifecycle events, as stated above a browser changing tabs shouldn't require a `pause` event imho

**Comment by janpio** [comment]
Ok, but what is crashing? Or did you mean "clash"?
Even then I don't understand how something from `cordova-android` is relevant for `cordova-browser`? Or does browser implement the current stuff right now?

**Comment by benitogf** [comment]
in the browser `resume` and `pause` are called on visibility change, think that it could further filter the trigger to actual lifecycle events like `freeze` and `resume`, the reason why I included the link to cordova-android docs is because I couldn't find a lifecycle specification for cordova-browser

**Comment by janpio** [comment]
I am not even sure if there is any special lifecycle handling for `cordova-browser` - it probably comes from the browser itself I guess. But we will have to look into the code further here.

So your issue is more like a feature request to better integrate the page lifecycle API you linked to, and not about a problem or bug that currently exists?

**Comment by benitogf** [comment]
would consider it a bug rather than a new feature since there's already an implementation in `cordova-browser` but not sure

regardless of an integration with the page lifecycle API,  a visibility change should trigger  `pause` ?

my experience was that implementing lifecycle events works fine on android but made the application "pause" on every tab change when deployed to the browser

**Comment by janpio** [comment]
> my experience was that implementing lifecycle events works fine on android but made the application "pause" on every tab change when deployed to the browser

Ah, now we are getting concrete. That is not normal browser behavior?

**Comment by benitogf** [comment]
> That is not normal browser behavior?

Is not in my opinion, but open to different ideas

**Comment by janpio** [comment]
The easiest way to find out (and also later to test and verify any implementation in `cordova-browser`) would be a super simple Cordova app / `index.html` that outputs the events that are occuring either in the console or in a div on a page. 

Could you create one of those and put them on GitHub? (Bonus points if you follow these instructions for a minimal reproduction repository: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md - because that will minimize the time we contributors have to spend to set this up.)

**Comment by benitogf** [comment]
Hello @janpio  I got around this by checking the user agent before adding the event listener to filter the desktop browser which works even for the webview build (https://developer.chrome.com/multidevice/user-agent):

```js
if (navigator.userAgent.match(/Android|iPhone|iPad|iPod/i)) {
   document.addEventListener('pause', () => {})
   document.addEventListener('resume', () => {})
}
```

I realize that the page lifecycle events are not implemented on other browsers and that some applications might depend on current behavior of `cordova-browser` events so closing this one for now, thanks
