### ISSUE TITLE
plugin.xml is missing

### ISSUE THREAD

**Issue by sertal70** [apache/cordova-browser#83]
# Bug Report

## Problem
Cannot install plugin in my project

### What is expected to happen?
When I execute the install command `cordova plugin add cordova-browser --save` the plugin is installed in my project.

### What does actually happen?
When I execute the install command `cordova plugin add cordova-browser --save` the cordova-cli prints the error message `Cannot find plugin.xml for plugin "cordova-browser"`. Running the command with `--verbose` option I get the following output:
```shell
$ cordova plugin add cordova-browser --verbose --save
No scripts found for hook "before_plugin_add".
No version specified for cordova-browser, retrieving version from config.xml
No version for cordova-browser saved in config.xml or package.json
Attempting to use npm info for cordova-browser to choose a compatible release
npm info for cordova-browser did not contain any engine info. Fetching latest release
Calling plugman.fetch on plugin "cordova-browser"
saving
Running command: npm install cordova-browser --production --save
Command finished with error code 0: npm install,cordova-browser,--production,--save
Error: Cannot find plugin.xml for plugin "cordova-browser". Please try adding it again.
```

### Command or Code
`cordova plugin add cordova-browser --save`

### Version information
I'm working on a Ionic project:
```

Ionic:

   ionic (Ionic CLI)  : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.7
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 6.4.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.1, (and 19 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/Sergio/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v8.9.3 (/usr/local/bin/node)
   npm               : 5.10.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.1 Build version 11A1027
```

## Checklist

- [X ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by erisu** [comment]
`cordova-browser` is not a plugin and will not have a `plugin.xml` file. This is a platform repo.

**Comment by sertal70** [comment]
Thanks @erisu su and please accept my apologies, I've be get confused with another plugin having similar name.
