### ISSUE TITLE
https? cordova run browser

### ISSUE THREAD

**Issue by jviure** [apache/cordova-browser#89]
Hi! sorry if my question is stupid BUT, I've an api where I've to acces through ssl, it's possible to launch the server under ssl? like https://localhost:8000

Thanks!

**Comment by breautek** [comment]
Short answer is no, cordova doesn't support serving certificates.

I'm not certain on this, but I believe `cordova run` / `cordova serve` is intended to be used for development, not for production use. If this is the case, I don't foresee this being added as a feature.

However you can run a reverse proxy server using NGINX or Apache that serves SSL certificates, then you proxy_pass to the cordova server.

**Comment by timbru31** [comment]
Closing this issue as Norman has answered the question 👍
