### ISSUE TITLE
favicon overwrite

### ISSUE THREAD

**Issue by MiguelQueiroz** [apache/cordova-browser#93]
# Bug Report
I have a favicon.ico in my root project file, and also in the www folder just in case, And during build browser, that icon gets replaced by the default cordova icon, the little box...  Why it does not copy what i already have in my project folder
### What is expected to happen?
Preserve / copy my favicon to the new platform/browser folder

### What does actually happen?
It replaces the favicon with the default cordova one.

### Command or Code

cordova build browser

### Environment, Platform, Device

Browser

### Version information
9.0.0

## Checklist

- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by MiguelQueiroz** [comment]
False alarm, the weird thing is that windows icon kept showing the preview of the old icon, but opening i could check it was updated. 


![image](https://user-images.githubusercontent.com/2479868/80140224-8ec83080-859f-11ea-9913-597473854cd7.png)

**Comment by Polm90** [comment]
I have the same issue.
I've opened the file and it's still the cordova one.

I'm using cordova 10.0.0 and cordova-browser 6.0.0
